sudo: required

language: bash

addons:
  apt:
    packages:
      - docker-ce
      - w3m

env:
  global:
    - IMAGE=${IMAGE}
    - IMAGE_NAME="${DOCKER_NAMESPACE}/${IMAGE}"

before_script:
  - sudo sysctl -w net.ipv4.ip_forward=1
  - export UBUNTU_VERSION="18.10"
  
script: |
  docker build \
          --no-cache \
          --pull \
          --quiet \
          --build-arg UBUUNTU_VERSION="${UBUNTU_VERSION}" \
          --tag "${IMAGE_NAME}:latest" \
          --tag "${IMAGE_NAME}:${UBUNTU_VERSION}" \
          --file "${TRAVIS_BUILD_DIR}/Dockerfile" \
          "${TRAVIS_BUILD_DIR}"
  if [[ "${TRAVIS_BRANCH}" == "master" ]] && [[ "${TRAVIS_PULL_REQUEST}" == "false" ]]; then
    docker login -u "${DOCKER_USER}" -p "${DOCKER_PASSWORD}"
    docker push "${IMAGE_NAME}:${UBUNTU_VERSION}"
    docker push "${IMAGE_NAME}:latest"
  fi
